package:
  name: xkeyboard-config
  version: 2.13


download:
  url: http://xorg.freedesktop.org/releases/individual/data/xkeyboard-config
  file_tar_bz2: ~
  checksum: 7b5be9f2b9a30102512b15308aec55f7f54289df24ac21de82ebb4bf145f9fce

version: ~

linux:

  - build:
    - configure_kx: >
        --with-xkb-rules-symlink=xorg
        --enable-compat-rules=yes
    - make: ~

  # 'make check' does nothing

  - install:
    - install: ~     

